### ISSUE TITLE
Manually specify devservice port

### ISSUE THREAD

**Issue by rasmushaglund** [quarkiverse/quarkus-amazon-services#794]
I would like to be able to manually specify port for the S3 devservice in the config. I'm using S3 to upload and serve static files for a web site and thus need to get the complete devservice url. 

From what I understand this is not possible today since the localstack container port is randomized. I've tried to change the external port and edge port for localstack with `container-properties` but I don't think I can affect the external port for the docker container in that way.

Would it make sense to add a config entry for this, like other dev services have? I'll gladly help if I get some pointer on where this port is set. Or maybe it's possible to expose the service urls through a config entry.

**Comment by rasmushaglund** [comment]
I just found out that I can use `quarkus.s3.endpoint-override` to get the full url, is this enough, or are there also use cases for manually specifying port? Otherwise maybe it suffices with just updating the documentation in case others are looking for the same information.

**Comment by scrocquesel** [comment]
> I just found out that I can use `quarkus.s3.endpoint-override` to get the full url, is this enough, or are there also use cases for manually specifying port? Otherwise maybe it suffices with just updating the documentation in case others are looking for the same information.

Sorry for late reply, yes, you can use the properties set by dev services. If you need those properties in a test class, you can use [DevServicesContext](https://quarkus.io/guides/getting-started-testing#testing-dev-services).

If you want to propose a PR to manualy set the exposed port, that would be great addition. You may look at https://github.com/quarkiverse/quarkus-amazon-services/blob/main/common/deployment/src/main/java/io/quarkus/amazon/common/deployment/DevServicesLocalStackProcessor.java to process a config property defined in https://github.com/quarkiverse/quarkus-amazon-services/blob/main/common/runtime/src/main/java/io/quarkus/amazon/common/runtime/LocalStackDevServicesBuildTimeConfig.java. This must be a property for the whole stack because each service are exposed on the same port, and an internal port can be exposed only once. Let me know if you need more guidance.

**Comment by pfaul** [comment]
Hello, I just opened a PR to address this issue.
My setup is a little different, nevertheless I want to configure an exposable port for the localstack docker container.
I opted for a generic solution, so I just added the option to pass a String as a command to the docker container.
https://github.com/quarkiverse/quarkus-amazon-services/pull/1114

**Comment by dagrammy** [comment]
Hi @scrocquesel,

I have opened a PR to address the problem. I look forward to your feedback.
