### ISSUE TITLE
Request: Please add s3-transfer-manager

### ISSUE THREAD

**Issue by Jeansen** [quarkiverse/quarkus-amazon-services#894]
I'd be happy to see https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/transfer-manager.html available in the quarkus realm.

**Comment by scrocquesel** [comment]
We would need to complete https://github.com/quarkiverse/quarkus-amazon-services/issues/860 first.

**Comment by scrocquesel** [comment]
If things goes well, you should be able to add a dependency on `io.quarkus:quarkus-amazon-crt` instead of `software.amazon.awssdk.crt:aws-crt`directly and follow the rest of the guide to create an instance manually. You can wrap it in a producer method if you need CDI support of `S3TransferManager`.

**Comment by Jeansen** [comment]
OK, I'll try that out.

**Comment by argenstijn** [comment]
What is the status?

**Comment by scrocquesel** [comment]
I finally managed to have a working solution for both `netty`/`aws-crt` http based client and `@S3Crt` based client in native build.
It is still experimental. I plan to merge the PR and have a build release by the end of the week. If you have time to look into the PR and do some beta testing, that would be warmly welcomed.

I opend [an issue ](https://github.com/aws/aws-sdk-java-v2/issues/4841) at aws sdk for the S3Crt client. If the injected bean is first access from within a future produced by the S3CrtAsyncClient, the TCCL cannot load some classes. I guess it happens only during dev/test mode due to the way class loader works in Quarkus.
